kind: pipeline
type: kubernetes
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world
- name: fr
  image: alpine
  commands:
  - echo bonjour monde
- name: cn
  image: alpine
  commands:
  - echo tianhan1939
trigger:
  branch:
  - develop
