kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: test
  image: golang:1.12
  commands:
  - go build
  - go test
