kind: pipeline
type: kubernetes
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world
- name: fr
  image: alpine
  commands:
  - echo bonjour monde
- name: cn
  image: alpine
  commands:
  - echo tianhan1939
trigger:
  branch:
  - develop

---
kind: pipeline
type: kubernetes
name: cron_test

steps:
- name: cron_step1
  image: alpine
  commands:
  - echo hello world
- name: cron_step2
  image: alpine
  commands:
  - echo bonjour monde
trigger:
  branch:
  - master
  event:
  - cron
  cron:
  - cron_test
